version: '3.4'

services:
  auth_web:
    build:
      args:
        NPM_TOKEN: ${NPM_TOKEN}
      context: .
      target: build
    entrypoint: ./entrypoint_development.sh
    ports:
      - 8001:8001
    volumes:
      - ./:/usr/src/app:delegated
    tty: true
    stdin_open: true
    env_file:
      - .env
    environment:
      - CHOKIDAR_USEPOLLING=true
